FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace

ARG SERVICE_DIR

COPY pom.xml .
COPY platform ./platform
COPY services ./services

RUN mvn -pl ${SERVICE_DIR} -am -DskipTests package
RUN find ${SERVICE_DIR}/target -maxdepth 1 -name "*.jar" -not -name "*-original.jar" -print -quit | xargs -I {} cp {} /tmp/app.jar

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /tmp/app.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
