ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500),
  ADD COLUMN IF NOT EXISTS bio VARCHAR(280),
  ADD COLUMN IF NOT EXISTS about TEXT,
  ADD COLUMN IF NOT EXISTS pronouns VARCHAR(80),
  ADD COLUMN IF NOT EXISTS location_label VARCHAR(120),
  ADD COLUMN IF NOT EXISTS website_url VARCHAR(320);
