#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<'EOSQL'
\set AUTH_DB_USER :ENV:AUTH_DB_USER
\set AUTH_DB_PASSWORD :ENV:AUTH_DB_PASSWORD
\set AUTH_DB_NAME :ENV:AUTH_DB_NAME
\set SOCIAL_DB_USER :ENV:SOCIAL_DB_USER
\set SOCIAL_DB_PASSWORD :ENV:SOCIAL_DB_PASSWORD
\set SOCIAL_DB_NAME :ENV:SOCIAL_DB_NAME
\set LISTS_DB_USER :ENV:LISTS_DB_USER
\set LISTS_DB_PASSWORD :ENV:LISTS_DB_PASSWORD
\set LISTS_DB_NAME :ENV:LISTS_DB_NAME
\set PINS_DB_USER :ENV:PINS_DB_USER
\set PINS_DB_PASSWORD :ENV:PINS_DB_PASSWORD
\set PINS_DB_NAME :ENV:PINS_DB_NAME
\set MODERATION_DB_USER :ENV:MODERATION_DB_USER
\set MODERATION_DB_PASSWORD :ENV:MODERATION_DB_PASSWORD
\set MODERATION_DB_NAME :ENV:MODERATION_DB_NAME

CREATE USER :"AUTH_DB_USER" WITH PASSWORD :'AUTH_DB_PASSWORD';
CREATE USER :"SOCIAL_DB_USER" WITH PASSWORD :'SOCIAL_DB_PASSWORD';
CREATE USER :"LISTS_DB_USER" WITH PASSWORD :'LISTS_DB_PASSWORD';
CREATE USER :"PINS_DB_USER" WITH PASSWORD :'PINS_DB_PASSWORD';
CREATE USER :"MODERATION_DB_USER" WITH PASSWORD :'MODERATION_DB_PASSWORD';

CREATE DATABASE :"AUTH_DB_NAME" OWNER :"AUTH_DB_USER";
CREATE DATABASE :"SOCIAL_DB_NAME" OWNER :"SOCIAL_DB_USER";
CREATE DATABASE :"LISTS_DB_NAME" OWNER :"LISTS_DB_USER";
CREATE DATABASE :"PINS_DB_NAME" OWNER :"PINS_DB_USER";
CREATE DATABASE :"MODERATION_DB_NAME" OWNER :"MODERATION_DB_USER";
EOSQL
